name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: llmretriever.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Data Simulator
      uses: docker/build-push-action@v2
      with:
        context: ./data_simulator
        push: true
        tags: llmretriever.azurecr.io/data-simulator:latest

    - name: Build and push Data Retriever
      uses: docker/build-push-action@v2
      with:
        context: ./data_retriever
        push: true
        tags: llmretriever.azurecr.io/data-retriever:latest

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd infrastructure/terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd infrastructure/terraform
        terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    - name: Get Data Retriever IP
      run: |
        cd infrastructure/terraform
        echo "Data Retriever IP: $(terraform output -raw data_retriever_ip)"