name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Create .env file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
        echo "API_PORT=${{ secrets.API_PORT }}" >> .env
        echo "RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}" >> .env

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: llmretriever.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Data Simulator
      uses: docker/build-push-action@v2
      with:
        context: ./data_simulator_temp
        push: true
        tags: llmretriever.azurecr.io/data-simulator:latest

    - name: Build and push Data Retriever
      uses: docker/build-push-action@v2
      with:
        context: ./data_retriever
        push: true
        tags: llmretriever.azurecr.io/data-retriever:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd infrastructure/terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd infrastructure/terraform
        terraform apply -auto-approve

    - name: Get Data Retriever IP
      run: |
        cd infrastructure/terraform
        echo "Data Retriever IP: $(terraform output -raw data_retriever_ip)"